
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_terapia
#spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.dvjkxquflyyzfptlnpwx&password=Las7encore20*
spring.datasource.username=postgres
spring.datasource.password=postgres



